[package]
name = "afg_guessing_game"
version = "0.1.0"
edition = "2021"
description = "A guessing game written in Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
